name: Bradford CoderDojo
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 20
paginate_path: "blog/page:num"
encoding: utf-8

gems: [jekyll-paginate]

exclude:
  - Gemfile
  - Gemfile.lock


